version: 2
updates:
  # Maintain dependencies for github-actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly

  # Maintain dependencies for yarn
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
