version: '3.8'
services:
  test-db:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecosense-db
    networks:
      - ecosense-test
networks:
  ecosense-test:
