name: Cache Node.js Build
on:
  schedule:
    # Every Sunday at 00:30 UTC+7
    - cron: '30 17 * * 6'
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  cache:
    name: Cache with Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: node-cache-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            node-cache-${{ runner.os }}-yarn-

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
