name: Lockfile Maintenance
on: workflow_dispatch

jobs:
  run:
    name: Lockfile
    uses: KenTandrian/workflows/.github/workflows/lockfile.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      package-manager: yarn
      base-version: 2
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
