name: Lockfile Maintenance
on:
  schedule:
    # Every Sunday at 00:00 UTC+7
    - cron: '0 17 * * 6'
  workflow_dispatch:

jobs:
  run:
    name: Lockfile
    uses: KenTandrian/workflows/.github/workflows/lockfile.yml@main
    permissions:
      contents: write
    with:
      package-manager: yarn
      base-version: 2
    secrets: inherit
