name: Pull Request Reviewer
on: pull_request_target

permissions:
  pull-requests: write
  contents: write
  repository-projects: read

jobs:
  review-dependabot-pr:
    name: PR Review
    uses: KenTandrian/workflows/.github/workflows/dependabot-reviewer.yml@main

  approve-lockfile-pr:
    name: PR Approve
    if: github.event.sender.login == 'github-action[bot]' && contains(github.event.pull_request.title, 'lockfile maintenance')
    uses: KenTandrian/workflows/.github/workflows/approve-automerge.yml@main
